services:
  - type: web
    name: voters-insight
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr poppler-utils && \
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
