services:
  - type: web
    name: pdf-insight-app
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y $(cat packages.txt)
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=8080 --server.enableCORS=false
